import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
let modelsData = "{}"
let skipWrite = false

try {
  modelsData = process.env.MODELS_DEV_API_JSON
    ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
    : await fetch(`${modelsUrl}/api.json`).then((x) => {
        if (!x.ok) throw new Error(`HTTP ${x.status} ${x.statusText}`);
        return x.text();
      })
} catch (err: any) {
  console.warn(`Failed to fetch models from ${modelsUrl}/api.json: ${err.message}`)
  const existingPath = path.join(dir, "src/provider/models-snapshot.js")
  if (await Bun.file(existingPath).exists()) {
    console.warn("Using existing models-snapshot.js")
    skipWrite = true
  }
}

if (!skipWrite) {
  await Bun.write(
    path.join(dir, "src/provider/models-snapshot.js"),
    `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
  )
  await Bun.write(
    path.join(dir, "src/provider/models-snapshot.d.ts"),
    `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
  )
  console.log("Generated models-snapshot.js")
}
